<li>
                            	<a href="[field:arcurl/]" class="img_wrap" target="_blank"><img src="[field:picname/]" width="176" height="135" /></a>
                                <div class="text-area">
                                    <p>[field:title/]</p>
                                    <p><a href="[field:typeurl/]" target="_blank">[field:typename/]</a></p>
                                    <p>价格：<span class="p-num">[field:needmoney/]</span> 元</p>
                                </div>
                            </li>