<li class="group"> 
      <div class="gallery thumb"> 
       <a href="[field:arcurl/]">
       <img data-original="[field:picname/]" src="[field:global.cfg_cmsurl/]/skin/1.0/images/original300x300.png" width="300" height="300" alt="[field:title/]"> 
        <div class="gallery-ico">
         <i class="fa fa-link"></i>
        </div> 
        <div class="gallery-mask"></div> </a> 
      </div> 
      <div class="meta"> 
       <div class="title"> 
        <a href="[field:arcurl/]" rel="bookmark" title="[field:title/]">[field:title/]</a> 
       </div> 
       <div class="extra"> 
        <time class="time"><i class="fa fa-date"></i> 
        	[field:pubdate function="MyDate('Y-m-d',@me)"/]
        </time> 
        <span class="comment-num" title="[field:dows/]人下载"><i class="fa fa-dows"></i>[field:dows/]</span>
        <span class="view-num" title="[field:click/]人浏览"><i class="fa fa-eye"></i>[field:click/]</span>
        <span class="heart-num" title="[field:stows/]人收藏"><i class="fa fa-shopping-cart_stows"></i>[field:stows/]</span> 
       </div> 
      </div> </li>