<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="6";
$z[0][4]['value']="3";
$z[1]=Array("img"," http://up.a0218.com/uploads/allimg/151226/1-151226023T9.png ",93,306);
$z[1][4]['ddimg']="http://up.a0218.com/uploads/allimg/151226/1-151226023T9-lp.png";
$z[1][4]['text']="请直接查看程序演示";
$z[1][4]['width']="800";
$z[1][4]['height']="831";

?>