<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:daccess islist="1" itemname="下载级别" type="int" isnull="true" default="0" rename="" function="" notsend="1"/>	
<field:softsize  itemname="软件大小" type="text" isnull="true" default="" rename="" />	
<field:needmoney islist="1" itemname="需要金币" type="int" isnull="true" default="0" rename="" function="" notsend="1" />
<field:softlinks  itemname="软件地址" type="softlinks" isnull="true" default="" rename="" />
