<li class="group"> 
       <div class="item"> 
        <div class="thumb"> 
         <a href="[field:arcurl/]" title="[field:fulltitle/]"> <img width="280" height="180" alt="[field:title/]" data-original="[field:picname/]" src="[field:global.cfg_cmsurl/]/skin/1.0/images/original.png" /> </a> 
        </div> 
        <div class="meta"> 
         <div class="title">
          <h2><a href="[field:arcurl/]" rel="bookmark" title="[field:title/]">[field:title/]</a></h2>
         </div> 
         <div class="extra"> 
          <i class="fa fa-bookmark"></i> 
          <a href="[field:typeurl/]" rel="category tag">[field:typename/]</a> 
          <span>[field:click/]<i class="fa fa-fire"></i></span> 
         </div> 
        </div> 
        <div class="data"> 
         <time class="time">
         <i class="fa fa-date"></i>
            [field:pubdate function="MyDate('Y-m-d',@me)"/]
         </time> 
         <span class="comment-num" title="[field:dows/]人下载"><i class="fa fa-dows"></i>[field:dows/]</span> 
         <span class="heart-num" title="[field:stows/]人收藏"><i class="fa fa-shopping-cart_stows"></i>[field:stows/]</span> 
        </div> 
       </div> </li>