<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:daccess islist="1" itemname="下载级别" type="int" isnull="true" default="0" rename="" function="" notsend="1"/>	
<field:softsize  itemname="软件大小" type="text" isnull="true" default="" rename="" />	
<field:needmoney islist="1" itemname="需要金币" type="int" isnull="true" default="0" rename="" function="" notsend="1" />
<field:softlinks  itemname="软件地址" type="softlinks" isnull="true" default="" rename="" />
<field:demo_url itemname="演示地址" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:demo_url>
<field:mbfl itemname="模板分类" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="企业模板,其它"  maxlength="250" page="">
</field:mbfl>
<field:mbbh itemname="模板编号" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="QM-0000"  maxlength="25" page="">
</field:mbbh>
<field:panpwd itemname="解压密码" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="70" page="">
</field:panpwd>

<field:webcms itemname="建站程序" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="帝国CMS,织梦CMS,WordPress,phpcms,discuz!,ecshop,其它"  maxlength="10" page="">
</field:webcms>
