<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="6";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/160717/1-160GG34249.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/160717/1-160GG34249-lp.jpg";
$z[1][4]['text']="1";
$z[1][4]['width']="500";
$z[1][4]['height']="332";
$z[2]=Array("img"," /uploads/allimg/160717/1-160GG34253.jpg ",242,390);
$z[2][4]['ddimg']="/uploads/allimg/160717/1-160GG34253-lp.jpg";
$z[2][4]['text']="2";
$z[2][4]['width']="1280";
$z[2][4]['height']="854";
$z[3]=Array("img"," /uploads/allimg/160717/1-160GG34256.jpg ",392,540);
$z[3][4]['ddimg']="/uploads/allimg/160717/1-160GG34256-lp.jpg";
$z[3][4]['text']="3";
$z[3][4]['width']="1280";
$z[3][4]['height']="850";

?>