<?php
$z[0]=Array("global","",230,255);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("field","",610,627);
$z[1][4]['name']="aid";
$z[2]=Array("global","",688,713);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",774,799);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",865,890);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("field","",1309,1330);
$z[5][4]['name']="pinglun";
$z[6]=Array("global","",1476,1501);
$z[6][4]['name']="cfg_cmsurl";

?>