<?php
$z[0]=Array("top","\r\n    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />\r\n    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />\r\n    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />\r\n    ",51,399);
$z[0][4]['name']="模块管理";
$z[0][4]['c']="6,";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />\r\n<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />\r\n<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />\r\n<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />\r\n<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />\r\n<m:item name='XML地图生成' link='map.php' rank='plus_starget='main' />\r\n<m:item name=\"百度结构化数据\" link=\"baidusitemap_main.php\" rank=\"plus_百度结构化数据\" target=\"main\" />\r\n\r\n",401,1319);
$z[1][4]['item']="7";
$z[1][4]['name']="辅助插件";
$z[1][4]['display']="block";
$z[2]=Array("top","\r\n  <m:item name='参数设置' link='qqLogin.php?ac=setting' rank='sys_MakeHtml' target='main' />\r\n  <m:item name='织梦二次开发网' link='http://www.dedevvip.com' rank='sys_MakeHtml' target='_blank' />\r\n",1323,1607);
$z[2][4]['name']="QQ一键登录助手";
$z[2][4]['c']="1,";
$z[2][4]['display']="block";
$z[2][4]['rank']="";

?>