<?php
$z[0]=Array("arcurl","",24,39);
$z[1]=Array("picname","",89,105);
$z[2]=Array("global","",112,138);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("title","",181,195);
$z[4]=Array("arcurl","",235,250);
$z[5]=Array("title","",273,287);
$z[6]=Array("title","",289,303);
$z[7]=Array("pubdate","",406,453);
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("dows","",515,528);
$z[9]=Array("needmoney","",588,606);

?>