<li> 
        <a href="[field:arcurl/]" target="_blank" class="img"><img data-original="[field:picname/]" src="[field:global.cfg_cmsurl/]/skin/1.0/images/original269x269.png" alt="[field:title/]" width="270" /></a>
      <p><a href="[field:arcurl/]" class="title" title="[field:title/]">[field:title/]</a></p>
      <div class="data"> 
         <time class="time"><i class="fa fa-date"></i>
         	[field:pubdate function="MyDate('Y-m-d',@me)"/]
         </time> 
         <span><i class="fa fa-dows"></i>[field:dows/]</span> 
         <!--span><i class="fa fa-money-list"></i>[field:needMoney/].00</span--> 
       </div> </li>