<?php
$z[0]=Array("field","",256,275);
$z[0][4]['name']="title";
$z[1]=Array("global","",317,342);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",421,446);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",553,578);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",839,864);
$z[4][4]['name']="cfg_smcurl";
$z[5]=Array("field","",871,887);
$z[5][4]['name']="id";
$z[6]=Array("field","",894,913);
$z[6][4]['name']="title";
$z[7]=Array("global","",986,1011);
$z[7][4]['name']="cfg_smcurl";
$z[8]=Array("field","",1018,1034);
$z[8][4]['name']="id";
$z[9]=Array("global","",1124,1147);
$z[9][4]['name']="cfg_zxkf";
$z[10]=Array("productimagelist","\n    <a href=\"javascript:void(0);\" dimg=\"[field:imgsrc/]\">[field:text/]</a>\n    ",1285,1412);
$z[11]=Array("field","",1524,1576);
$z[11][4]['name']="aid";
$z[11][4]['function']="Getimgs(@me,400,300,1)";
$z[12]=Array("field","",1585,1604);
$z[12][4]['name']="title";
$z[13]=Array("field","",1611,1630);
$z[13][4]['name']="title";
$z[14]=Array("arclist","\n                            <li>\n                            	<a href=\"[field:arcurl/]\" class=\"img_wrap\" target=\"_blank\"><img src=\"[field:picname/]\" width=\"176\" height=\"135\" /></a>\n                                <div class=\"text-area\">\n                                    <p>[field:title/]</p>\n                                    <p><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></p>\n                                    <p>价格：<span class=\"p-num\">[field:needmoney/]</span> 元</p>\n                                </div>\n                            </li>\n                            ",2024,2716);
$z[14][4]['row']="10";
$z[14][4]['typeid']="7";
$z[14][4]['addfields']="needmoney";
$z[14][4]['channelid']="4";

?>