<li> <a class="thumb" href="[field:arcurl/]" title="[field:title/]"> <img width="80" height="80" alt="[field:title/]" src="[field:picname/]" /> </a> 
          <div class="meta"> 
           <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a> 
           <span><a href="[field:arcurl/]#respond" class="comments-link">[field:pinglun/]评论</a><i class="click">[field:click/]点击</i></span> 
          </div> </li>