<?php
$z[0]=Array("global","",224,249);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",753,778);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",808,834);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",946,971);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1001,1027);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1065,1090);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      ",1152,1396);
$z[6][4]['type']="top";
$z[6][4]['row']="5";
$z[6][4]['currentstyle']="<li class='current-menu-item current_page_item'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[7]=Array("type","<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>",1463,1555);
$z[7][4]['typeid']="5";
$z[8]=Array("type","<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",1618,1710);
$z[8][4]['typeid']="24";
$z[9]=Array("global","",1733,1760);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",1760,1785);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("global","",2409,2434);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("hotwords","",3155,3209);
$z[12][4]['num']="15";
$z[12][4]['subday']="365";
$z[12][4]['maxlength']="16";

?>