<?php
$typeArr[16] = '企业模板';
$typeArr[4] = '网站轮播';
$typeArr[5] = '通知';
$typeArr[6] = '公告';
$typeArr[7] = '网站模板';
$typeArr[11] = '安装方法';
$typeArr[9] = '自助服务';
$typeArr[12] = '常见问题';
$typeArr[15] = '官方活动';
$typeArr[17] = '商城模板';
$typeArr[20] = 'CMS插件';
$typeArr[21] = '织梦插件';
$typeArr[22] = '折扣信息';
$typeArr[23] = 'HTML5模板';
$typeArr[24] = '留言联系';
$typeArr[25] = '手机模板';
$typeArr[26] = '素材站模板';
$typeArr[27] = '视频素材站';
$typeArr[28] = '五指CMS';
?>